#!/bin/sh
export DOCKER_CLI_EXPERIMENTAL=enabled
#docker pull -q multiarch/qemu-user-static
#docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
#docker buildx create --name multibuilder --driver docker-container --use

#DOCKER_CLI_EXPERIMENTAL=enabled docker buildx create --name multibuilder
#DOCKER_CLI_EXPERIMENTAL=enabled docker buildx use multibuilder
#DOCKER_CLI_EXPERIMENTAL=enabled docker buildx install
docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag erseco/alpine-php7-webserver:beta .
