#!/bin/bash
# Register qemu-*-static for all supported processors except the
# current one, but also remove all registered binfmt_misc before

export DOCKER_CLI_EXPERIMENTAL=enabled
# docker pull -q multiarch/qemu-user-static
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes
docker buildx create --name multibuilder --driver docker-container --use


# docker run --rm --privileged multiarch/qemu-user-static:register --reset
